Implemented profile to be user-specific and refactored profile-related files
CMPUT301W23T09/QRHunter pull request #38
Opened 2023-03-06 18:29 UTC by IreneRSun

2023-03-06 18:56 UTC, WillQizza approved these changes
LGTM!

2023-03-06 20:46 UTC, WillQizza submitted a review, later dismissed

2023-03-07 16:03 UTC, jmmabanta requested changes
Add docstings to the non-overrided methods/new methods you made just so our javadoc is up-to-date. Otherwise LGTM!

2023-03-08 05:02 UTC, jmmabanta approved these changes
On a completely separate note, is the auto formatter working for you? I saw that you made a manual formatting commit but it should format the files automatically right before a commit goes through so it isn't necessary. 

Also you may want to talk with @FrancesIgwe on how we should implement adding/removing QR codes on the model/db side since I've been mostly working on the frontend for the camera scanning

Otherwise LGTM

2023-03-08 10:56 UTC, WillQizza approved these changes

2023-03-08 10:56 UTC, merged