Allow viewing other player profiles + leaderboard UI tests
CMPUT301W23T09/QRHunter pull request #61
Opened 2023-03-28 05:59 UTC by WillQizza

The following pull request will close the following: #6 and #12 

This pull request implements the following...
- Splits `ProfileFragment` and `ProfileController` into `MyProfile...` and `OtherProfile...` variants
- Tests for the LeaderboardFragment
- Fixed issue where removing a QR would not autorefresh the profile QR list
- Fixed issue where `<GameController>.getPopup` would return `null` constantly
- Adds static utility method to `BaseTest` to retrieve the device UUID of the player or autogenerate one

2023-03-29 21:59 UTC, IreneRSun requested changes
I get this error whenever I navigate to the social page
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.cmput301w23t09.qrhunter, PID: 5702
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
        at java.util.UUID.fromString(UUID.java:192)
        at com.cmput301w23t09.qrhunter.player.PlayerDatabase.snapshotToPlayer(PlayerDatabase.java:272)
        at com.cmput301w23t09.qrhunter.player.PlayerDatabase.lambda$getAllPlayers$8$com-cmput301w23t09-qrhunter-player-PlayerDatabase(PlayerDatabase.java:257)
        at com.cmput301w23t09.qrhunter.player.PlayerDatabase$$ExternalSyntheticLambda3.onComplete(Unknown Source:4)
        at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

2023-03-29 22:08 UTC, IreneRSun submitted a review, later dismissed
Since the previous issue I brought up was just an issue on the database side, lgtm!

2023-03-30 04:37 UTC, IreneRSun approved these changes

2023-03-30 04:45 UTC, jmmabanta approved these changes

2023-03-30 05:02 UTC, merged